### ISSUE TITLE
Failed to compile cache with SWR v^1

### ISSUE THREAD

**Issue by AshishKapoor** [jjordy/swr-devtools#23]
Getting this issue with SWR v1+, and node version v14.17.0

```
Failed to compile.

./node_modules/@jjordy/swr-devtools/esm/SWRDevtools/Cache.js 2:9
Module parse failed: Unexpected token (2:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export default class DevToolsCache {
>   __cache;
|   __listeners;
|
```

**Comment by AshishKapoor** [comment]
Yep!
```
        <SWRConfig value={{ provider: () => new Cache() }}>
            <SWRDevtools />
            <App />
        </SWRConfig>
```

**Comment by jjordy** [comment]
Yeh that looks good can you tell me a little about your project so I can try to reproduce this issue? I am not having this issue in any of my projects using the latest version. My implementation looks identical so I can only guess this is something with a difference in the way we build are projects. Are you using typescript or no?

**Comment by AshishKapoor** [comment]
Yes, I'm making use of Typescript. 

> Are you using typescript or no?

**Comment by jjordy** [comment]
I checked in a few things I thought could potentially affect the module in your environment but I installed the package in a few different environment types in code sandbox and everything seemed to be working fine. So without seeing your exact build setup / project I'm not sure I will be able to help much. Its possible the change I just made for 2.0.7 will fix your issue but Im not positive.

**Comment by AshishKapoor** [comment]
> I checked in a few things I thought could potentially affect the module in your environment but I installed the package in a few different environment types in code sandbox and everything seemed to be working fine. So without seeing your exact build setup / project I'm not sure I will be able to help much. Its possible the change I just made for 2.0.7 will fix your issue but Im not positive.

No luck. 😞 However, thanks for giving it a shot anyway. 🙂

**Comment by AshishKapoor** [comment]
> @AshishKapoor I have made some improvements to the way The library works if you would like to try it again hopefully it will work for you now the implementation has changed a bit again. (Hopefully for the last time).

Sure. Will do. 🙂
